# Use the official Node.js 16 image as the base image
FROM node:16 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application to the working directory
COPY . .

# Build the Angular application
RUN npm run build --configuration=development

# Use the official Nginx image as the base image for serving the application
FROM nginx:alpine

# Copy the built Angular application from the build stage to the Nginx html directory
COPY --from=build /app/dist/OSDRepeatAutumn2023 /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
